# Generated by Django 3.0.8 on 2021-03-03 10:00

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('base_price', models.IntegerField()),
                ('category', models.CharField(choices=[('Home & Kitchen', 'Home & Kitchen'), ('Electronics', 'Electronics'), ('Books', 'Books'), ('Toys', 'Toys'), ('Fashion', 'Fashion'), ('Antiques', 'Antiques'), ('Automobile', 'Automobile')], max_length=50)),
                ('image_url', models.CharField(max_length=1000)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('closing_date', models.DateField(blank=True, default=datetime.date(2021, 3, 18))),
                ('owner', models.ManyToManyField(blank=True, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
