# Generated by Django 3.0.8 on 2021-03-06 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210303_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closing_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 21)),
        ),
    ]
