# Generated by Django 3.0.8 on 2021-03-12 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210310_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='owner',
        ),
        migrations.AlterField(
            model_name='listing',
            name='closing_date',
            field=models.DateField(blank=True, default=datetime.date(2021, 3, 27)),
        ),
    ]
